"""siet add dns

Revision ID: 2a32e310c6ba
Revises: None
Create Date: 2015-08-18 07:10:29.005127

"""

# revision identifiers, used by Alembic.
revision = '2a32e310c6ba'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('dns', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'dns')
    ### end Alembic commands ###
