"""ippool add sales

Revision ID: 2e71623de6cc
Revises: 2a32e310c6ba
Create Date: 2015-09-08 03:07:02.821038

"""

# revision identifiers, used by Alembic.
revision = '2e71623de6cc'
down_revision = '2a32e310c6ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ippool', sa.Column('sales', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ippool', 'sales')
    ### end Alembic commands ###
