"""users alais

Revision ID: 3c8b0c5ff618
Revises: 44f310ecd708
Create Date: 2015-09-18 18:44:23.555255

"""

# revision identifiers, used by Alembic.
revision = '3c8b0c5ff618'
down_revision = '44f310ecd708'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alias', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'alias')
    ### end Alembic commands ###
