"""add task

Revision ID: 44f310ecd708
Revises: 2e71623de6cc
Create Date: 2015-09-15 13:54:10.307920

"""

# revision identifiers, used by Alembic.
revision = '44f310ecd708'
down_revision = '2e71623de6cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('task', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_author'), 'task', ['author'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_author'), table_name='task')
    op.drop_table('task')
    ### end Alembic commands ###
