"""ippopl delete netmask

Revision ID: 55ab2e990ea0
Revises: 3c8b0c5ff618
Create Date: 2015-09-21 16:39:35.909879

"""

# revision identifiers, used by Alembic.
revision = '55ab2e990ea0'
down_revision = '3c8b0c5ff618'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ippool', 'netmask')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ippool', sa.Column('netmask', mysql.VARCHAR(length=64), nullable=True))
    ### end Alembic commands ###
